# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "."
  t.test_files = FileList["test_shacl_*.rb"]
  t.warning = false
  # -W0 (sets $VERBOSE = nil) silences noisy "literal string will be frozen
  # in the future" notices from the shacl gem's dependencies (ebnf, sxp) on
  # newer Rubies -- t.warning = false alone doesn't stop them, since they
  # aren't gated by $VERBOSE = false, only by $VERBOSE = nil.
  t.ruby_opts = ["-W0"]
  t.verbose = true
end

task default: :test
