PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

select  ?comment 
        ?equivalent 
        ?label 
        ?subClassOf 

from <http://schema.org/#8.0>

where { 
    OPTIONAL {schema:Event    rdfs:comment        ?comment .} 
    OPTIONAL {schema:Event    rdfs:label          ?label .} 
    OPTIONAL {schema:Event    rdfs:subClassOf     ?subClassOf .}  
} 