# Merges the files that describe the Artsdata CORE graph data model --
# ontology/artsdata-ontology.ttl, shacl/shacl_artsdata_core.ttl and
# shacl/shacl_artsdata_ontology.ttl -- into a single self-contained Turtle
# file at the repo root (artsdata-schema.ttl), so that external tools --
# e.g. an MCP server's get_schema tool -- can fetch one stable URL instead
# of combining files themselves.
#
# shacl/shacl_artsdata.ttl (validates raw external submissions to the
# Databus) is intentionally NOT included: it targets a different graph.
#
# Also regenerates schema-overview/index.html (see generate_schema_overview.rb)
# from the freshly written artsdata-schema.ttl, so the two files never drift
# apart.
#
# Usage:
#   cd _generators
#   bundle install   # first time only
#   bundle exec ruby generate_mcp_schema.rb

class GenerateMcpSchema
  SOURCE_FILES = %w[
    ../ontology/artsdata-ontology.ttl
    ../shacl/shacl_artsdata_core.ttl
    ../shacl/shacl_artsdata_ontology.ttl
  ].freeze

  OUTPUT_FILE = '../artsdata-schema.ttl'

  PREFIX_LINE = /\A@prefix\s+(\w[\w-]*):\s+<([^>]+)>\s*\.\s*\z/.freeze

  def self.run
    prefixes = {}
    sections = SOURCE_FILES.map do |path|
      full_path = File.join(File.dirname(__FILE__), path)
      lines = File.readlines(full_path, chomp: true)
      body_start = lines.index { |line| !line.match?(PREFIX_LINE) && !line.strip.empty? }

      lines[0...body_start].each do |line|
        match = PREFIX_LINE.match(line)
        next unless match

        name, uri = match.captures
        if prefixes.key?(name) && prefixes[name] != uri
          raise "Conflicting @prefix #{name}: #{prefixes[name]} vs #{uri} (in #{path})"
        end

        prefixes[name] = uri
      end

      body = lines[body_start..].join("\n").rstrip
      [File.basename(path), body]
    end

    output = +"# GENERATED FILE -- do not edit directly.\n"
    output << "# Generated by _generators/generate_mcp_schema.rb from:\n"
    SOURCE_FILES.each { |path| output << "#   #{path.sub('../', '')}\n" }
    output << "#\n"
    output << "# Combines the Artsdata Ontology (classes, properties, vocabulary\n"
    output << "# equivalences) with the Artsdata CORE graph SHACL shapes and the\n"
    output << "# Artsdata Ontology SHACL shapes into one self-contained file, for\n"
    output << "# consumers (e.g. an MCP server's schema tool) that want the full\n"
    output << "# data model of the reconciled Artsdata CORE graph in a single fetch.\n\n"

    prefixes.sort.each do |name, uri|
      output << "@prefix #{name}: <#{uri}> .\n"
    end
    output << "\n"

    sections.each do |filename, body|
      output << "####################################################\n"
      output << "# From #{filename}\n"
      output << "####################################################\n\n"
      output << body
      output << "\n\n"
    end

    out_path = File.join(File.dirname(__FILE__), OUTPUT_FILE)
    File.write(out_path, output.rstrip + "\n")
    puts "Generated #{OUTPUT_FILE}."
  end
end

GenerateMcpSchema.run
require_relative 'generate_schema_overview'
